version: '3.3'

services:
  web:
    build:
      context: ../../
      dockerfile: docker/photostorage/Dockerfile
    env_file: .app.env
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"

  db:
    image: postgres:${POSTGRES_IMAGE_TAG:-12.2}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-photos}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./configs/dumps/pg:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:${REDIS_IMAGE_TAG:-5}-alpine
    volumes:
      - redis-data:/data

volumes:
  pg-data:
    driver: local

  redis-data:
    driver: local
