version: '3.3'

# DOCKER_RUBY_VERSION: 2.7
# POSTGRES_VERSION: 13.1
# REDIS_VERSION: 6
# NGINX_VERSION=1.19.3
# POSTGRES_DB: photos
# GO_VERSION=1.14.2

services:
  web:
    build:
      context: ../../
      dockerfile: docker/photostorage/Dockerfile
      args:
        DOCKER_RUBY_VERSION: ${DOCKER_RUBY_VERSION:-2.7}
    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
      - sender
    volumes:
      - static-files:/photostorage/public
      - upload:/photostorage/tmp/files
    healthcheck:
      test: ["CMD", "curl", "--fail", "localhost:3000/api/v1/readiness"]
      timeout: 10s

  sidekiq:
    build:
      context: ../../
      dockerfile: docker/photostorage/Dockerfile
      args:
        DOCKER_RUBY_VERSION: ${DOCKER_RUBY_VERSION:-2.7}
    env_file: .env
    depends_on:
      - db
      - redis
      - web
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - upload:/photostorage/tmp/files
    external_links:
      - nginx

  db:
    image: postgres:${POSTGRES_VERSION:-13.1}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-photos}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./configs/dumps/pg:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:${REDIS_VERSION:-6}-alpine
    volumes:
      - redis-data:/data

  proxy:
    build:
      context: ../../
      dockerfile: docker/photostorage/Dockerfile.proxy
      args:
        GO_VERSION: ${GO_VERSION:-1.14.2}
    depends_on:
      - db
      - web

  sender:
    build:
      context: .
      dockerfile: Dockerfile.sender
      args:
        GO_VERSION: ${GO_VERSION:-1.14.2}
    env_file: .env

  nginx:
    image: nginx:${NGINX_VERSION:-1.19.3}-alpine
    depends_on:
      - web
      - proxy
    volumes:
      - static-files:/home/photos/public
      - cache:/var/cache/nginx
      - ./templates/nginx.conf:/etc/nginx/nginx.conf
      - ./templates/default.conf.template:/etc/nginx/conf.d/default.conf.template
    env_file: .env
    environment:
      - RAILS_HOST=web
      - PROXY_HOST=proxy
    ports:
      - "8080:8080"
    command: >
      /bin/sh -c "FRONT_HOST=$$(echo -n $$HOST | sed -r 's/\:[0-9]+$$//') \
        envsubst '$$$$RAILS_HOST $$$$FRONT_HOST $$$$PROXY_HOST' < /etc/nginx/conf.d/default.conf.template > \
        /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      default:
        aliases:
          - photos.localhost
          - www.photos.localhost

volumes:
  pg-data:
    driver: local

  redis-data:
    driver: local

  static-files:
    driver: local

  cache:
    driver: local

  upload:
    driver: local
