version: '2'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.${DOCKER_RUBY_VERSION}
    environment:
      - BUNDLE_PATH=/bundle/${DOCKER_RUBY_VERSION}
      - SSH_AUTH_SOCK=/ssh/auth/sock
      - TEST_DB_HOST=${POSTGRES_HOST}
      - TEST_DB_NAME=${POSTGRES_DB}
      - TEST_DB_USERNAME=postgres
      - RAILS_ENV=$RAILS_ENV
    command: bash

  web:
    extends:
      service: app
    command: 'bash -c "rm -f /var/run/rails.pid && bundle exec rails s -p 80 -b 0.0.0.0 --pid /var/run/rails.pid"'
    depends_on:
      - db
      - redis
    expose:
      - "80"

  db:
    image: postgres:${POSTGRES_IMAGE_TAG}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    image: redis:$REDIS_IMAGE_TAG

  sidekiq:
    extends:
      service: app
    command: 'bundle exec sidekiq -C config/sidekiq.yml'
    depends_on:
      - db
      - redis

  proxy:
    image: golang:$GO_IMAGE_TAG
    working_dir: /app
    volumes:
      - .:/app
      - ../../go:/go
    command: 'go run proxy_service/main.go'
    expose:
      - '9000'
