version: '3.3'

services:
  app: &app
    volumes:
      - ..:/app
      - ../../gems:/localgems
      - ssh-data:/ssh:ro
      - bundler-data:/bundle
    networks:
      - default
      - frontend
    environment:
      - EDITOR=nano
      - BROWSER=/bin/cat

  web:
    <<: *app
    stdin_open: true
    tty: true
    environment:
      - VIRTUAL_HOST=*.photostorage.$DOCKER_TLD
      - VIRTUAL_PATH=/

  sidekiq:
    <<: *app

  db:
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./configs/dumps/$RAILS_ENV/pg:/docker-entrypoint-initdb.d:ro

  redis:
    volumes:
      - redis-data:/data

  proxy:
    volumes:
      - ..:/app
    networks:
      - default
      - frontend
    dns: $DIP_DNS
    environment:
      - VIRTUAL_HOST=proxy.photostorage.$DOCKER_TLD
      - VIRTUAL_PATH=/

volumes:
  bundler-data:
    external:
      name: bundler_data

  ssh-data:
    external:
      name: ssh_data

  pg-data:
    driver: local

  redis-data:
    driver: local

networks:
  frontend:
    external:
      name: frontend
